//! MoleOption Solana program.
//!
//! This crate is the on-chain wrapper around the host-tested `clearing-core`
//! engine. Account validation, PDA derivation, and SPL transfer plumbing
//! live here; the math is deferred to `clearing-core` to ensure the host
//! tests and the on-chain runtime share the exact same code path.
//!
//! BUILD NOTES
//!
//! This crate is **excluded** from the workspace root `Cargo.toml` because
//! it depends on `anchor-lang` and `anchor-spl`, which require the Solana
//! BPF / SBF toolchain. To build:
//!
//! ```text
//! # Install once
//! sh -c "$(curl -sSfL https://release.anza.xyz/stable/install)"
//! cargo install --git https://github.com/coral-xyz/anchor avm --locked
//! avm install 0.31.0 && avm use 0.31.0
//!
//! # Build the program
//! cd programs/mole-option
//! anchor build
//! ```
//!
//! `anchor build` produces `target/deploy/mole_option.so`.

#![allow(clippy::result_large_err)]
// Anchor's `#[program]` and `#[derive(Accounts)]` macros expand into
// code that conditionally references `cfg(target_os = "solana")`,
// `cfg(feature = "anchor-debug")`, `cfg(custom-heap)`, and
// `cfg(custom-panic)` — none of which are declared in this crate's
// `[features]` table. Rust 1.80+'s `unexpected_cfgs` lint surfaces
// every macro emission as a warning; under `-D warnings` they become
// hard errors. Since we can't edit anchor's macros, allow them
// crate-wide. If we ever start using these cfgs in our own code,
// remove this allow and gate explicitly.
#![allow(unexpected_cfgs)]
// Anchor 0.31's `#[program]` macro expands to a body that calls
// `AccountInfo::realloc` (deprecated in favour of `resize` in newer
// solana-program). The deprecation is in macro-emitted code we don't
// control; pinning to a newer Anchor version would be a separate
// upgrade. Allow at the crate level so `-D warnings` stays usable for
// real lints in our own code.
#![allow(deprecated)]

use anchor_lang::prelude::*;

pub mod error;
pub mod instructions;
pub mod state;

pub use error::ProgramError;
// Glob re-export at the crate root so Anchor's `#[program]` macro can
// resolve `crate::__client_accounts_<X>` modules generated by every
// `#[derive(Accounts)]` inside `instructions::*`. The
// `ambiguous_glob_reexports` allow muffles the harmless name-collision
// between handler function names re-exported here AND the wrapper
// functions `#[program]` synthesises inside `mod mole_option` — both
// resolve to the same definition transitively, so the ambiguity is
// stylistic only and never affects callers.
#[allow(ambiguous_glob_reexports)]
pub use instructions::*;
pub use state::*;

// Placeholder program ID — the system-program all-zero address. `anchor
// keys list` will replace this with a real ED25519 pubkey on first
// deploy. We deliberately use the 32-`1` form (32 zero bytes) because
// it's the only base58 string guaranteed to round-trip as a 32-byte
// `Pubkey`; visual placeholders containing the letter `O`, `0`, `I`, or
// `l` are rejected by the base58 alphabet, and "long" placeholders may
// silently decode to >32 bytes.
declare_id!("EWqyK5r4MyNaewo2s6nqLmZEVt4Xcx1yNT2dfFnTSfWp");

#[program]
pub mod mole_option {
    use super::*;

    /// Initialize the global protocol configuration.
    pub fn initialize_global_config(
        ctx: Context<InitializeGlobalConfig>,
        params: InitGlobalConfigParams,
    ) -> Result<()> {
        instructions::initialize_global_config(ctx, params)
    }

    /// Create a new market.
    pub fn initialize_market(
        ctx: Context<InitializeMarket>,
        params: InitMarketParams,
    ) -> Result<()> {
        instructions::initialize_market(ctx, params)
    }

    /// Create the market's SPL token vaults (vault + fee_vault) as PDAs.
    /// Must be called once after `initialize_market` before any
    /// `open_position` can settle collateral.
    pub fn initialize_market_vaults(ctx: Context<InitializeMarketVaults>) -> Result<()> {
        instructions::initialize_market_vaults(ctx)
    }

    /// Create a new sub-pool inside a market.
    pub fn initialize_sub_pool(
        ctx: Context<InitializeSubPool>,
        sub_pool_id: u32,
    ) -> Result<()> {
        instructions::initialize_sub_pool(ctx, sub_pool_id)
    }

    /// Materialise the per-`(sub_pool, direction)` distribution
    /// ledger PDA. Must be called once before any `sync_pool` /
    /// `close_position` / `force_close` / `claim_dormant_recovery`
    /// hits the same `(sub_pool, direction)` for the first time.
    /// Idempotent on the PDA (Anchor's `init` rejects re-init).
    pub fn initialize_distribution_ledger(
        ctx: Context<InitializeDistributionLedger>,
        direction_is_long: bool,
    ) -> Result<()> {
        instructions::initialize_distribution_ledger(ctx, direction_is_long)
    }

    /// Materialise an empty `DormantBucket` PDA at the given
    /// `(sub_pool, direction, zero_price_tick)`. The PDA is required
    /// before the engine's `insert_or_merge` can land a new bucket on
    /// chain. The keeper / front-end pre-allocates these whenever a
    /// `PositionRotated` event suggests a new tick is about to be
    /// touched. See `Docs/Planning/23-on-chain-dormant-bridge.md` for
    /// the exact lifecycle.
    pub fn initialize_dormant_bucket(
        ctx: Context<InitializeDormantBucket>,
        direction_is_long: bool,
        zero_price_tick: i64,
    ) -> Result<()> {
        instructions::initialize_dormant_bucket(ctx, direction_is_long, zero_price_tick)
    }

    /// Public sync_pool. Anyone may call to keep a sub-pool fresh.
    ///
    /// Wave 6 contract: `remaining_accounts` carries `long_bucket_count`
    /// long-side `DormantBucket` PDAs followed by `short_bucket_count`
    /// short-side ones. Both `long_ledger` and `short_ledger` are
    /// passed via the named account fields. See
    /// `instructions::sync::SyncPool` doc-comment for the full layout
    /// contract.
    pub fn sync_pool<'info>(
        ctx: Context<'_, '_, 'info, 'info, SyncPool<'info>>,
        envelope: PriceEnvelopeArgs,
        long_bucket_count: u32,
        short_bucket_count: u32,
    ) -> Result<()> {
        instructions::sync_pool(ctx, envelope, long_bucket_count, short_bucket_count)
    }

    /// Open a new position.
    pub fn open_position(ctx: Context<OpenPosition>, params: OpenParams) -> Result<()> {
        instructions::open_position(ctx, params)
    }

    /// Close a position. Active and recovery shares are both redeemed.
    ///
    /// Wave 7 contract: same dormant-bridge `remaining_accounts` shape
    /// as [`Self::sync_pool`] (long_buckets ++ short_buckets). The
    /// `long_ledger` / `short_ledger` PDAs are passed via the named
    /// account fields. See `instructions::close::ClosePosition` doc.
    pub fn close_position<'info>(
        ctx: Context<'_, '_, 'info, 'info, ClosePosition<'info>>,
        envelope: PriceEnvelopeArgs,
        long_bucket_count: u32,
        short_bucket_count: u32,
    ) -> Result<()> {
        instructions::close_position(ctx, envelope, long_bucket_count, short_bucket_count)
    }

    /// Force-close a position whose total redeemable would be zero.
    ///
    /// Wave 7 contract: identical to [`Self::close_position`].
    pub fn force_close_zero_value_position<'info>(
        ctx: Context<'_, '_, 'info, 'info, ForceClosePosition<'info>>,
        envelope: PriceEnvelopeArgs,
        acknowledge_forfeit: bool,
        long_bucket_count: u32,
        short_bucket_count: u32,
    ) -> Result<()> {
        instructions::force_close_zero_value_position(
            ctx,
            envelope,
            acknowledge_forfeit,
            long_bucket_count,
            short_bucket_count,
        )
    }

    /// Redeem the recovery shares accrued on a dormant position.
    ///
    /// Wave 7 contract: identical to [`Self::close_position`].
    pub fn claim_dormant_recovery<'info>(
        ctx: Context<'_, '_, 'info, 'info, ClaimDormantRecovery<'info>>,
        envelope: PriceEnvelopeArgs,
        long_bucket_count: u32,
        short_bucket_count: u32,
    ) -> Result<()> {
        instructions::claim_dormant_recovery(ctx, envelope, long_bucket_count, short_bucket_count)
    }

    /// Lazy-mode keeper catch-up: drain pending distribution-ledger
    /// entries onto a single dormant bucket. Permissionless; the
    /// engine's invariant check guards against malicious input.
    ///
    /// Wave 7 contract: same `remaining_accounts` shape as
    /// [`Self::sync_pool`]. The chosen bucket MUST appear in the
    /// corresponding direction's slice.
    pub fn pre_sync_dormant_bucket<'info>(
        ctx: Context<'_, '_, 'info, 'info, PreSyncDormantBucket<'info>>,
        direction_is_long: bool,
        bucket_tick: i64,
        long_bucket_count: u32,
        short_bucket_count: u32,
    ) -> Result<()> {
        instructions::pre_sync_dormant_bucket(
            ctx,
            direction_is_long,
            bucket_tick,
            long_bucket_count,
            short_bucket_count,
        )
    }

    /// Sweep accumulated dust from a sub-pool to the protocol fee vault.
    pub fn harvest_dust(ctx: Context<HarvestDust>, direction_is_long: bool) -> Result<()> {
        instructions::harvest_dust(ctx, direction_is_long)
    }

    /// Close a zero-state dormant bucket PDA and refund its rent.
    /// Permissionless. See `instructions::init::CloseDormantBucket`.
    pub fn close_dormant_bucket(ctx: Context<CloseDormantBucket>) -> Result<()> {
        instructions::close_dormant_bucket(ctx)
    }

    /// Emergency pause. Restricted to `EmergencyAuthority`.
    pub fn pause_market(ctx: Context<PauseMarket>) -> Result<()> {
        instructions::pause_market(ctx)
    }

    /// Emergency resume. Restricted to `EmergencyAuthority`.
    pub fn resume_market(ctx: Context<PauseMarket>) -> Result<()> {
        instructions::resume_market(ctx)
    }

    /// Freeze new opens (graceful market deprecation).
    pub fn freeze_new_position(ctx: Context<PauseMarket>) -> Result<()> {
        instructions::freeze_new_position(ctx)
    }

    /// Wave 9 — counterpart to `freeze_new_position`. Restricted to
    /// `EmergencyAuthority`. Without this the freeze flag would be a
    /// one-way door.
    pub fn unfreeze_new_position(ctx: Context<PauseMarket>) -> Result<()> {
        instructions::unfreeze_new_position(ctx)
    }

    /// Wave 9 — toggle the cross-market kill switch. Restricted to
    /// `AdminAuthority` (the slow-multisig authority). The flag lives
    /// on `GlobalConfig`; per-market `Market::paused` is unchanged.
    pub fn set_globally_paused(
        ctx: Context<AdminGlobalAccounts>,
        paused: bool,
    ) -> Result<()> {
        instructions::set_globally_paused(ctx, paused)
    }

    /// Wave 9 — bump `Market::schema_version`. Restricted to
    /// `AdminAuthority`. Always called *after* `migrate_market` (and
    /// `migrate_position` for every outstanding position) under the
    /// same governance proposal — see `Docs/Planning/16-治理与升级.md`.
    pub fn bump_market_schema_version(
        ctx: Context<AdminMarketAccounts>,
        new_version: u16,
    ) -> Result<()> {
        instructions::bump_market_schema_version(ctx, new_version)
    }

    /// Wave 9 — walk a `Position`'s data shape up to
    /// `SCHEMA_VERSION_CURRENT`. Permissionless: anyone can drive a
    /// position forward, paying the small compute fee. Reject path
    /// keeps users honest — protocol-side rejection
    /// (`SchemaVersionMismatch`) means a position MUST migrate before
    /// any `close_position` / `claim_dormant_recovery` succeeds.
    pub fn migrate_position(ctx: Context<MigratePosition>) -> Result<()> {
        instructions::migrate_position(ctx)
    }

    /// Wave 9 — walk a `Market`'s data shape up to
    /// `SCHEMA_VERSION_CURRENT`. Restricted to `AdminAuthority` so
    /// the migration tx and the `bump_market_schema_version` tx
    /// share the same governance timelock.
    pub fn migrate_market(ctx: Context<MigrateMarket>) -> Result<()> {
        instructions::migrate_market(ctx)
    }

    /// **Wave 15.** Initialise the per-market keeper-leader lock PDA.
    /// Permissionless; any wallet can pay rent. Lock starts unowned.
    /// See `instructions::keeper_leader` for the full lifecycle
    /// + `Docs/Planning/24-operator-runbook.md` for ops.
    pub fn initialize_keeper_leader_lock(
        ctx: Context<InitializeKeeperLeaderLock>,
    ) -> Result<()> {
        instructions::initialize_keeper_leader_lock(ctx)
    }

    /// **Wave 15.** Strict claim-stale path for HA keeper takeovers.
    /// Rejects if the lock is currently fresh.
    pub fn keeper_leader_acquire(
        ctx: Context<KeeperLeaderHeartbeat>,
        args: KeeperLeaderHeartbeatArgs,
    ) -> Result<()> {
        instructions::keeper_leader_acquire(ctx, args)
    }

    /// **Wave 15.** All-paths heartbeat — acquires fresh, takes over
    /// from stale, refreshes self, or rejects with the right reason.
    /// Drives the keeper bot's normal tick path.
    pub fn keeper_leader_heartbeat(
        ctx: Context<KeeperLeaderHeartbeat>,
        args: KeeperLeaderHeartbeatArgs,
    ) -> Result<()> {
        instructions::keeper_leader_heartbeat(ctx, args)
    }

    /// **Wave 15.** Graceful release. Holder relinquishes the lock so
    /// a standby keeper doesn't have to wait
    /// `takeover_threshold_slots` slots before claiming leadership.
    pub fn keeper_leader_release(ctx: Context<KeeperLeaderRelease>) -> Result<()> {
        instructions::keeper_leader_release(ctx)
    }
}
